### ISSUE TITLE
BSCachingAllocator的kMinAllocationSize可以用环境变量来控制吗？

### ISSUE THREAD

**Issue by aimsky** [DeepLink-org/DIPU#236]
当前BS的kMinAllocationSize固定为512，且所有分配的空间都会做512对齐，可能会造成一定的空间浪费，期望也可以用环境变量来控制。

**Comment by zhaoguochun1995** [comment]
可以用环境变量来控制。在内存不够用的时候可以减小kMinAllocationSize。在内存够时还是建议512字节对齐

**Comment by zhaoguochun1995** [comment]
相关代码已合并
